version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: unicorn-commander:${TAG:-latest}
    container_name: unicorn-commander
    restart: unless-stopped
    network_mode: host
    environment:
      - NGINX_PORT=${PORT:-8081}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
  
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: unicorn-commander-api:${TAG:-latest}
    container_name: unicorn-commander-api
    restart: unless-stopped
    network_mode: host
    environment:
      - PORT=3000
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-unicorn123}
    volumes:
      - ./database.sqlite:/app/database.sqlite
